// Generated by pixel-studio from presets.json. Regenerate instead of editing.
export const PRESETS = {
  "soft-system": {
    "palette": {
      "ink": "#17170F",
      "moss-deep": "#2E3722",
      "moss": "#5E6B48",
      "moss-soft": "#9AA97C",
      "fawn": "#D6C0A0",
      "blush": "#D9A398",
      "haze": "#A9BAC0",
      "bone-2": "#E9E3D3",
      "bone": "#F2EEE3",
      "signal": "#A9F50D",
      "flare": "#DC3A1E",
      "pug-mask": "#3B2E20"
    },
    "ramps": {
      "photo": [
        "ink",
        "moss-deep",
        "moss",
        "moss-soft",
        "fawn",
        "bone"
      ],
      "warm": [
        "ink",
        "moss-deep",
        "blush",
        "fawn",
        "bone"
      ],
      "moss": [
        "ink",
        "moss-deep",
        "moss",
        "moss-soft",
        "bone"
      ],
      "duotone": [
        "moss",
        "bone"
      ],
      "mark": [
        "ink",
        "bone"
      ],
      "terminal": [
        "#0D0F0A",
        "signal"
      ]
    },
    "default_ramp": "photo",
    "dither": "bayer4",
    "spread": 0.45,
    "width": 160,
    "scale": 4,
    "bg": "bone",
    "accent": "signal",
    "block": 0,
    "autocontrast": true
  },
  "gameboy": {
    "palette": {
      "d0": "#0F380F",
      "d1": "#306230",
      "d2": "#8BAC0F",
      "d3": "#9BBC0F"
    },
    "ramps": {
      "photo": [
        "d0",
        "d1",
        "d2",
        "d3"
      ]
    },
    "default_ramp": "photo",
    "dither": "bayer4",
    "spread": 0.5,
    "width": 160,
    "scale": 4,
    "bg": "d3",
    "accent": "d0",
    "block": 1,
    "autocontrast": true
  },
  "mono": {
    "palette": {
      "black": "#000000",
      "white": "#FFFFFF"
    },
    "ramps": {
      "photo": [
        "black",
        "white"
      ]
    },
    "default_ramp": "photo",
    "dither": "atkinson",
    "spread": 0.5,
    "width": 200,
    "scale": 3,
    "bg": "white",
    "accent": "black",
    "block": 1,
    "autocontrast": true
  },
  "fibo": {
    "palette": {
      "ink": "#0A0A0A",
      "paper": "#F2F2F0",
      "white": "#FFFFFF"
    },
    "ramps": {
      "mono": [
        "ink",
        "paper"
      ]
    },
    "default_ramp": "mono",
    "dither": "bayer8",
    "spread": 0.5,
    "width": 168,
    "scale": 6,
    "bg": "paper",
    "accent": "white",
    "block": 0,
    "autocontrast": true,
    "frame": {
      "size": [
        1080,
        1350
      ],
      "art": [
        34,
        34,
        1046,
        1206
      ],
      "paper": "paper",
      "ink": "ink",
      "cell": 6,
      "gap": 1,
      "wash": 0.12,
      "dots": {
        "color": "white",
        "spacing": 15,
        "radius": 0.36,
        "size": [
          3,
          7
        ]
      },
      "logo": "fibo-bunny.sprite",
      "logo_cell": 3,
      "logo_at": [
        34,
        1259
      ],
      "wordmark": "fibo",
      "wordmark_font": "Geist-Medium",
      "wordmark_size": 48,
      "wordmark_at": [
        112,
        1306
      ],
      "mono_font": "GeistMono-Regular",
      "mono_size": 21,
      "mono_baseline": 1305,
      "url": "fibo.toribryan.com",
      "soften": 2.5,
      "gamma": 0.4
    }
  },
  "fibo-hero": {
    "palette": {
      "ink": "#0A0A0A",
      "paper": "#F2F2F0",
      "white": "#FFFFFF"
    },
    "ramps": {
      "mono": [
        "ink",
        "paper"
      ]
    },
    "default_ramp": "mono",
    "dither": "bayer8",
    "spread": 0.5,
    "width": 168,
    "scale": 6,
    "bg": "paper",
    "accent": "white",
    "block": 0,
    "autocontrast": true,
    "frame": {
      "size": [
        1536,
        416
      ],
      "art": [
        0,
        0,
        1536,
        416
      ],
      "paper": "paper",
      "ink": "ink",
      "cell": 6,
      "gap": 1,
      "wash": 0.12,
      "dots": {
        "color": "white",
        "spacing": 13,
        "radius": 0.36,
        "size": [
          3,
          6
        ]
      },
      "logo": "fibo-bunny.sprite",
      "logo_cell": 3,
      "logo_at": [
        34,
        1259
      ],
      "wordmark": "fibo",
      "wordmark_font": "Geist-Medium",
      "wordmark_size": 48,
      "wordmark_at": [
        112,
        1306
      ],
      "mono_font": "GeistMono-Regular",
      "mono_size": 21,
      "mono_baseline": 1305,
      "url": "fibo.toribryan.com",
      "soften": 2.5,
      "gamma": 0.4
    }
  }
};
export const DEFAULT_PRESET = "soft-system";
