import type { SVGProps } from "react";

export type BadgeCheck2Outline24Props = SVGProps<SVGSVGElement>;

export function BadgeCheck2Outline24(props: BadgeCheck2Outline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M13 22L11 22" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 20L18 20" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M6 20L9 20" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M20 15L20 18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M10.01 15L10 15" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M4 15L4 18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M12.01 13L12 13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M8.01001 13L8.00001 13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M22 11L22 13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M14.01 11L14 11" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M2 11L2 13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M16.01 9L16 9" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M20 6L20 9" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M4 6L4 9" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 4L18 4" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M6 4L9 4" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M13 2L11 2" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path></svg>
  );
}
