import type { SVGProps } from "react";

export type BrightnessIncreaseOutline24Props = SVGProps<SVGSVGElement>;

export function BrightnessIncreaseOutline24(props: BrightnessIncreaseOutline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M12 21L12 23" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M20 20H20.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M4 20H4.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M18 18H18.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M6 18H6.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M11 17L13 17" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 15H15.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9 15H9.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M23.005 11.995L21.005 11.995" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M3.005 11.995L1.005 11.995" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M17 11L17 13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M6.99999 11L7 13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 9H15.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9 9H9.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M11 7.00001L13 7" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M18 6H18.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M6 6H6.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M20 4H20.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M4 4H4.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M12 1L12 3" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path></svg>
  );
}
