import type { SVGProps } from "react";

export type CircleCheckOutline24Props = SVGProps<SVGSVGElement>;

export function CircleCheckOutline24(props: CircleCheckOutline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M8 22L16 22" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M18.01 20L18 20" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M6.01001 20L6.00001 20" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M20.01 18L20 18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M4.01001 18L4.00001 18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M9.99999 15H10.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M12 13H12.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M7.99999 13H8.00999" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M14 11H14.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M16 9H16.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M22 8L22 16" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M2 8L2 16" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M20.01 6L20 6" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M4 6L4 6.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M18.01 4L18 4" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M6 4L6 4.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M8 2L16 2" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path></svg>
  );
}
