import type { SVGProps } from "react";

export type CircleQuestionOutline24Props = SVGProps<SVGSVGElement>;

export function CircleQuestionOutline24(props: CircleQuestionOutline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M8 22L16 22" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M18.01 20L18 20" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M6.01001 20L6.00001 20" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M20.01 18L20 18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M4.01001 18L4.00001 18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M12.01 17L12 17" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M12 13L13 13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 11L15 9" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9.01001 9L9.00001 9" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M22 8L22 16" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M2 8L2 16" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M11 7L13 7" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M20.01 6L20 6" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M4 6L4 6.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M18.01 4L18 4" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M6 4L6 4.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M8 2L16 2" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path></svg>
  );
}
