import type { SVGProps } from "react";

export type GraduationCapOutline24Props = SVGProps<SVGSVGElement>;

export function GraduationCapOutline24(props: GraduationCapOutline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M13 2H11" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M13 14H11" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9 4H7" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M17 4H15" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9 12H7" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M5 6H3" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M21 6H19" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M21 10H19" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M5 10H3" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M19 14V15" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M17 17V19" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M21 17V19" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M4 15V19" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M13 21L6 21" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M1 8V8.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M13 8V8.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 10V10.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M17 12V12.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M19 21V21.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M23 8V8.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path></svg>
  );
}
