import type { SVGProps } from "react";

export type GridLayoutOutline24Props = SVGProps<SVGSVGElement>;

export function GridLayoutOutline24(props: GridLayoutOutline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M19 21L16 21" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M8 21L5 21" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M21 19L21 19.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M14 19L14 19.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M19 17L16 17" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M19 13L16 13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M10 13L10 19" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M3 13L3 19" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M8 11L5 11" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M8 7L5 7" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M21 5L21 11" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M14 5L14 11" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M10 5L10 5.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M3 5L3 5.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M19 3L16 3" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M8 3L5 3" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path></svg>
  );
}
