import type { SVGProps } from "react";

export type PencilOutline24Props = SVGProps<SVGSVGElement>;

export function PencilOutline24(props: PencilOutline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M5 15H5.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M7 13H7.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9 11H9.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M11 9H11.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M13 7H13.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M7 17H7.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 9H15.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M15 5H15.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M17 3H17.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M19 5H19.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9 19H9.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M11 17H11.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M13 15H13.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 13H15.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M17 11H17.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M19 9H19.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M21 7H21.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M3 17V21H7" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path></svg>
  );
}
