import type { SVGProps } from "react";

export type PinOutline24Props = SVGProps<SVGSVGElement>;

export function PinOutline24(props: PinOutline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M8 2H16" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M11 7H13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M11 13H13" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M15 9L15 11" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M9 9L9 11" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M20 6L20 14" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M4 6L4 14" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M18 4.01001L18 4.00001" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M18 16.01L18 16" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M16 18.01L16 18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M14 20.01L14 20" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M12 22.01L12 22" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M10 20.01L10 20" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M8 18.01L8 18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M6 16.01L6 16" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M6 4.01001L6 4.00001" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path></svg>
  );
}
