import type { SVGProps } from "react";

export type RocketOutline24Props = SVGProps<SVGSVGElement>;

export function RocketOutline24(props: RocketOutline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M13 5H13.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 7H15.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M17 9H17.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M19 11H19.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M17 13H17.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M17 20H17.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M4 7H4.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 15H15.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9 9H9.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M11 15H11.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9 13H9.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M11 7H11.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M15 3H21V9" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M19 15V18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M9 5L6 5" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M13 17V22H15" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M7 11L2 11L2 9" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M5 16H6" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M8 19L8 18" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M3 18V21H6" stroke="currentColor" strokeWidth={2} strokeLinecap="square" data-color="color-2" fill="none"></path></svg>
  );
}
