import type { SVGProps } from "react";

export type Users2Outline24Props = SVGProps<SVGSVGElement>;

export function Users2Outline24(props: Users2Outline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><path d="M7 4H9" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" fill="none"></path> <path d="M7 10H9" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" fill="none"></path> <path d="M11 6L11 8" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" fill="none"></path> <path d="M5 6L5 8" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" fill="none"></path> <path d="M17.5 4H18.5" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M17.5 9H18.5" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M20.5 6L20.5 7" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M15.5 6L15.5 7" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M5 14H11" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" fill="none"></path> <path d="M16 13H20" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M1 18V20H15V18" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" fill="none"></path> <path d="M19 18H22V15" stroke="currentColor" strokeWidth={2} strokeMiterlimit="10" strokeLinecap="square" data-color="color-2" fill="none"></path> <path d="M3 16H3.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path> <path d="M13 16H13.01" stroke="currentColor" strokeWidth={2} strokeLinecap="square" fill="none"></path></svg>
  );
}
