import type { SVGProps } from "react";

export type XmarkOutline24Props = SVGProps<SVGSVGElement>;

export function XmarkOutline24(props: XmarkOutline24Props) {
  return (
    <svg xmlns="http://www.w3.org/2000/svg" width={24} height={24} viewBox="0 0 24 24" shapeRendering="crispEdges" {...props}><rect width={2} height={2} transform="matrix(-1 0 0 1 13 11)" fill="currentColor" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 11 9)" fill="currentColor" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 15 13)" fill="currentColor" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 15 9)" fill="currentColor" data-color="color-2" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 11 13)" fill="currentColor" data-color="color-2" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 9 15)" fill="currentColor" data-color="color-2" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 7 17)" fill="currentColor" data-color="color-2" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 5 19)" fill="currentColor" data-color="color-2" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 17 7)" fill="currentColor" data-color="color-2" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 19 5)" fill="currentColor" data-color="color-2" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 21 3)" fill="currentColor" data-color="color-2" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 19 17)" fill="currentColor" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 17 15)" fill="currentColor" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 21 19)" fill="currentColor" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 9 7)" fill="currentColor" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 7 5)" fill="currentColor" data-stroke="none"></rect> <rect width={2} height={2} transform="matrix(-1 0 0 1 5 3)" fill="currentColor" data-stroke="none"></rect></svg>
  );
}
